tup=()
fruit1=input("Enter the first fruit name:")
fruit2=input("Enter the second fruit name:")
fruit3=input("Enter the third fruit name:")
fruit4=input("Enter the fourth fruit name:")
fruit5=input("Enter the fifth fruit name:")
tup=(fruit1,fruit2,fruit3,fruit4,fruit5)
print(tup)
print(tup.index(fruit3))
print(len(tup))
print(tup.count(fruit3))