Line=input("Enter any sentence:")
print(Line)
print("Total Characters in the sentence are:",len(Line))
print("UpperCase version\n",Line.upper())
print("LowerCase version\n",Line.lower())
print("Count version\n",Line.count("a"))
print("replace version\n",Line.replace(" ","_"))
print("Title version\n",Line.title())
print("Capitalized version\n",Line.capitalize())
print("find version\n",Line.find("my"))